### ISSUE TITLE
Crossposter continuously fails jobs

### ISSUE THREAD

**Issue by commagray** [renatolond/mastodon-twitter-poster#312]
![image](https://user-images.githubusercontent.com/27947961/73120873-f27c9680-3f7b-11ea-9f6b-ef53cd457513.png)

I think it's not good. It loses some of my posts both from Mastodon and Twitter without any load (just 2 users). Most affected are posts with pictures from Mastodon to Twitter.

Can I somehow fix it? Increase the number of workers?

```
nightmare:
    image: lula.moonbutt.science/innereq/containers/crossposter
    restart: always
    env_file: .env
    command: bundle exec puma -C config/puma.rb
    networks:
      - proxy
      - internal
    depends_on:
      - db
    volumes:
      - /srv/containers/data/crossposter/assets:/opt/crossposter/public/assets
      - /srv/containers/data/crossposter/packs:/opt/crossposter/public/packs
    labels:
      - traefik.enable=true
      - traefik.backend=nightmare
      - traefik.docker.network=proxy
      - traefik.port=3001
      - traefik.frontend.rule=Host:nightmare.moonbutt.science
      - com.centurylinklabs.watchtower.enable=false

  sidekiq:
    image: lula.moonbutt.science/innereq/containers/crossposter
    restart: always
    env_file: .env
    command: bundle exec sidekiq -c 5 -q default
    depends_on:
      - db
    networks:
      - internal
    volumes:
      - /srv/containers/data/crossposter/assets:/opt/crossposter/public/assets
      - /srv/containers/data/crossposter/packs:/opt/crossposter/public/packs
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=false
```
